/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;

public class AppTest {
    @Ignore public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
